" ##################################################
" #   _    ___              _____       _      __  #
" #  | |  / (_)___ ___     / ___/____ _(_)__  / /  #
" #  | | / / / __ `__ \    \__ \/ __ `/ / _ \/ /   #
" #  | |/ / / / / / / /   ___/ / /_/ / /  __/ /    #
" #  |___/_/_/ /_/ /_/   /____/\__,_/_/\___/_/     #
" #                                                #
" ##################################################


": Vundle (plugins) {{{

filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'preservim/nerdtree'
Plugin 'majutsushi/tagbar'
Plugin 'leafgarland/typescript-vim'
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'
Plugin 'bling/vim-bufferline'
Plugin 'airblade/vim-gitgutter'
Plugin 'gcmt/taboo.vim'
Plugin 'mildred/vim-bufmru'
Plugin 'mkitt/tabline.vim'
Plugin 'mileszs/ack.vim'
Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-speeddating'
Plugin 'tpope/vim-commentary'
Plugin 'glts/vim-magnum'
Plugin 'glts/vim-radical'
Plugin 'ycm-core/YouCompleteMe'
Plugin 'ap/vim-css-color'
Plugin 'fatih/vim-go'

filetype plugin indent on

" }}}

" Plugin settings {{{

" Airline settings {{{

"let g:airline_solarized_bg = 'dark'
"let g:airline_solarized_dark_inactive_background = 1
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
autocmd vimenter * AirlineTheme ayu_mirage

" Airline settings }}}

" Bufferline settigns {{{
let g:bufferline_echo = 0
" }}}

" Vim-go settings {{{

" }}}

" Plugin settings }}}

" General editor settings {{{
set nocompatible

set shiftwidth=4
set softtabstop=4
set tabstop=4
set smarttab
set expandtab

set textwidth=88

set wildmenu

set updatetime=0

set ignorecase
set smartcase

set laststatus=2

set mouse=iv

set conceallevel=2

set foldmethod=indent

set autoread

set hidden

if version >= 700
    set history=64
    set undolevels=128
    set undodir=~/.vim/undodir/
    set undofile
    set undolevels=1000
    set undoreload=10000
endif

" }}}

" Appearance settings {{{

set ruler
set visualbell
set number
set signcolumn=yes
set foldcolumn=2
let g:gitgutter_sign_modified_removed = '~-'
let g:gitgutter_preview_win_floating = 1

set fillchars+=vert:│

" }}}

" Colorscheme {{{

"colorscheme default
"set background=dark
highlight Folded ctermbg=6 ctermfg=0
highlight SignColumn ctermbg=None
highlight foldcolumn ctermbg=None ctermfg=2
highlight VertSplit ctermbg=4 ctermfg=0

" }}}

" Keybidings {{{

map <C-Up> <C-y>
map <C-Down> <C-e>

map <F3> :NERDTreeToggle<CR>
map <F8> :TagbarToggle<CR>
map <A-Up> :BufMRUNext<CR>
map <A-Down> :BufMRUPrev<CR>

map <A-Right> :tabnext<CR>
map <A-Left> :tabprevious<CR>

nnoremap <silent> <C-_> :let @/ = ''<CR>

nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>

tnoremap <Esc> <C-\><C-n>

" Split management {{{

" navigation between splits
noremap <C-h> <C-w>h
noremap <C-j> <C-w>j
noremap <C-k> <C-w>k
noremap <C-l> <C-w>l

" resizing
noremap <silent> L :vertical resize +3<CR>
noremap <silent> H :vertical resize -3<CR>
noremap <silent> K :resize +3<CR>
noremap <silent> J :resize -3<CR>


" Split management }}}

" YCM keybindings {{{

" GoTo
nnoremap <F12> :YcmCompleter GoToDefinition<CR>
nnoremap <S-F12> :YcmCompleter GoToType<CR>

nnoremap <F11> :YcmCompleter GoToReference<CR>

nnoremap <F10> :YcmCompleter GoToImplementation<CR>
nnoremap <S-F10> :YcmCompleter GoToImplementation<CR>

nnoremap <Leader>gdd :YcmCompleter GoToDefinition<CR>
nnoremap <Leader>gde :YcmCompleter GoToDeclaration<CR>
nnoremap <Leader>gtt :YcmCompleter GoTo<CR>
nnoremap <Leader>gti :YcmCompleter GoToImprecise<CR>
nnoremap <Leader>gi :YcmCompleter GoToInclude<CR>
nnoremap <Leader>gr :YcmCompleter GoToReference<CR>
nnoremap <Leader>gT :YcmCompleter GoToType<CR>

" Semantic info
nnoremap <Leader>t :YcmCompleter GetTypeImprecise<CR>
nnoremap <Leader>T :YcmCompleter GetType<CR>
nnoremap <Leader>doc :YcmCompleter GetDoc<CR>
nnoremap <Leader>Doc :YcmCompleter GetDoc<CR>

" Refactoring
nnoremap <Leader>r :YcmCompleter RefactorRename 
nnoremap <Leader>ft :YcmCompleter Format<CR>
nnoremap <A-CR> :YcmCompleter FixIt<CR>

" YCM keybindings }}}

" Keybidings }}}

" vim:foldmethod=marker

